      SUBROUTINE F77HLO()
      INTEGER TID, NTHREADS
      include 'omp_lib.h'
      
C$OMP PARALLEL PRIVATE(TID)
      NTHREADS = OMP_GET_NUM_THREADS()
      TID = OMP_GET_THREAD_NUM()
      
      CALL INTPR("HELLO FROM THREAD", -1, TID, 1)
C$OMP END PARALLEL
      END SUBROUTINE

      SUBROUTINE F77SUM(X, XLEN, S)
      INTEGER XLEN
      DOUBLE PRECISION X(XLEN), S
      INTEGER I
      
      S = 0.0D0
C$OMP PARALLEL DO DEFAULT(SHARED) PRIVATE(I) REDUCTION(+:S)
      DO 10, I=1, XLEN
        S = S + X(I)
 10   CONTINUE
C$OMP END PARALLEL DO
      END SUBROUTINE

