# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_ <- function() {
    invisible(.Call('Romp_rcpp_hello_', PACKAGE = 'Romp'))
}

rcpp_sum_ <- function(x) {
    .Call('Romp_rcpp_sum_', PACKAGE = 'Romp', x)
}

rcpp_sweep_ <- function(x) {
    .Call('Romp_rcpp_sweep_', PACKAGE = 'Romp', x)
}

